name: swipable_stack
description: A widget for stacking cards, which users can swipe horizontally and vertically with beautiful animations.
version: 0.6.2
homepage: https://github.com/HeavenOSK/flutter_swipable_stack
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  state_notifier: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

