name: swipable_stack
description: A widget for stacking cards, which users can swipe horizontally and vertically with beautiful animations.
version: 0.0.2
homepage: https://github.com/HeavenOSK/flutter_swipable_stack
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: 1.10.0+3

